/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlinesmanagementsystem;

/**
 *
 * @author meetj
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        manageflight = new javax.swing.JButton();
        managepassenger = new javax.swing.JButton();
        ticketbooking = new javax.swing.JButton();
        ticketcancellation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        back.setText("BACK");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        dashboard.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        dashboard.setText("DASHBOARD");

        manageflight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageflight.setText("Manage Flight");
        manageflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageflightActionPerformed(evt);
            }
        });

        managepassenger.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        managepassenger.setText("Manage Passenger");
        managepassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managepassengerActionPerformed(evt);
            }
        });

        ticketbooking.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ticketbooking.setText("Ticket Booking");
        ticketbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketbookingActionPerformed(evt);
            }
        });

        ticketcancellation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ticketcancellation.setText("Ticket Cancellation");
        ticketcancellation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketcancellationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageflight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(managepassenger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ticketbooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ticketcancellation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(dashboard)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(back)
                .addGap(20, 20, 20)
                .addComponent(dashboard)
                .addGap(36, 36, 36)
                .addComponent(manageflight)
                .addGap(18, 18, 18)
                .addComponent(managepassenger)
                .addGap(18, 18, 18)
                .addComponent(ticketbooking)
                .addGap(18, 18, 18)
                .addComponent(ticketcancellation)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageflightActionPerformed
        // TODO add your handling code here:
        manageflights obj = new manageflights();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_manageflightActionPerformed

    private void managepassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managepassengerActionPerformed
        // TODO add your handling code here:
        managepassenger obj = new managepassenger();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_managepassengerActionPerformed

    private void ticketbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketbookingActionPerformed
        // TODO add your handling code here:
        ticketbooking obj = new ticketbooking();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ticketbookingActionPerformed

    private void ticketcancellationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketcancellationActionPerformed
        // TODO add your handling code here:
        ticketcancellation obj = new ticketcancellation();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ticketcancellationActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        LoginPage obj = new LoginPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel dashboard;
    private javax.swing.JButton manageflight;
    private javax.swing.JButton managepassenger;
    private javax.swing.JButton ticketbooking;
    private javax.swing.JButton ticketcancellation;
    // End of variables declaration//GEN-END:variables
}
